//#define USE_ONLY_BMP_WHEN_WAITING
//#define DONT_USE_THRUSTER_STABILIZATION
#define USE_LOOP_DELAY
#define LOG_DELTA 20
#define WARMING_TIME 2500
#define CALIBRATION_TIME 2500
#define THRUSTER_WORKING_TIME 15000
//#define USE_THRUSTER
#define AXIS_X_MIN 51
#define AXIS_X_MAX 121
#define AXIS_X_CENTER 86
#define AXIS_Z_MIN 61
#define AXIS_Z_MAX 126
#define AXIS_Z_CENTER 96
#define AXIS_ROTATION 0.0 // 45.0
